-- ===============LICENSE_START=======================================================
-- Acumos Apache-2.0
-- ===================================================================================
-- Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
-- ===================================================================================
-- This Acumos software file is distributed by AT&T and Tech Mahindra
-- under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--  
--      http://www.apache.org/licenses/LICENSE-2.0
--  
-- This file is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- ===============LICENSE_END=========================================================

-- Script to upgrade database used by the Common Data Service
-- FROM version 1.12.x TO version 1.13.x.
-- No database is created or specified to allow flexible deployment!
-- No databases were harmed in the testing of this script.

-- 1
INSERT INTO C_ACCESS_TYPE (TYPE_CD, TYPE_NAME) VALUES ('RS', 'Restricted');
-- 2
INSERT INTO C_TOOLKIT_TYPE (TYPE_CD, TYPE_NAME) VALUES ('PB', 'Probe');
-- 3
INSERT INTO C_TOOLKIT_TYPE (TYPE_CD, TYPE_NAME) VALUES ('TC', 'Training Client');
-- 4
INSERT INTO C_TOOLKIT_TYPE (TYPE_CD, TYPE_NAME) VALUES ('BR', 'Data Broker');
-- 5 
CREATE TABLE C_STEP_TYPE (
  TYPE_CD CHAR(2) NOT NULL PRIMARY KEY,
  TYPE_NAME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 6
INSERT INTO C_STEP_TYPE (TYPE_CD, TYPE_NAME) VALUES ('OB', 'Onboarding');
-- 7
INSERT INTO C_STEP_TYPE (TYPE_CD, TYPE_NAME) VALUES ('VL', 'Validation');
-- 8
CREATE TABLE C_SUB_SCOPE_TYPE (
  TYPE_CD CHAR(2) NOT NULL PRIMARY KEY,
  TYPE_NAME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 9
INSERT INTO C_SUB_SCOPE_TYPE (TYPE_CD, TYPE_NAME) VALUES ('RF', 'Reference');
-- 10
INSERT INTO C_SUB_SCOPE_TYPE (TYPE_CD, TYPE_NAME) VALUES ('FL', 'Full');
-- 11
CREATE TABLE C_STEP_STATUS (
  STATUS_CD CHAR(2) NOT NULL PRIMARY KEY,
  STATUS_NAME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 12
INSERT INTO C_STEP_STATUS (STATUS_CD, STATUS_NAME) VALUES ('FA', 'Failed');
-- 13
INSERT INTO C_STEP_STATUS (STATUS_CD, STATUS_NAME) VALUES ('ST', 'Started');
-- 14
INSERT INTO C_STEP_STATUS (STATUS_CD, STATUS_NAME) VALUES ('SU', 'Succeeded');
-- 15
CREATE TABLE C_PEER_STATUS (
  STATUS_CD CHAR(2) NOT NULL PRIMARY KEY,
  STATUS_NAME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 16
INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('AC', 'Active');
-- 17
INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('IN', 'Inactive');
-- 18
INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('PA', 'Pending Active');
-- 19
INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('RM', 'Removed');
-- 20
INSERT INTO C_PEER_STATUS (STATUS_CD, STATUS_NAME) VALUES ('PR', 'Pending Remove');
-- 21
ALTER TABLE C_PEER DROP COLUMN CONTACT2;
-- 22
ALTER TABLE C_PEER DROP COLUMN TRUST_LEVEL;
-- 23
ALTER TABLE C_PEER DROP COLUMN IS_ACTIVE;
-- 24
ALTER TABLE C_PEER MODIFY COLUMN WEB_URL VARCHAR(512) NULL;
-- 25
ALTER TABLE C_PEER
  ADD COLUMN IS_LOCAL CHAR(1) NOT NULL DEFAULT 'N';
-- 26
ALTER TABLE C_PEER
  ADD COLUMN STATUS_CD CHAR(2) NOT NULL DEFAULT 'IN',
  ADD CONSTRAINT C_PEER_C_PEER_STATUS FOREIGN KEY (STATUS_CD) REFERENCES C_PEER_STATUS (STATUS_CD);
-- 27
ALTER TABLE C_PEER
  ADD COLUMN VALIDATION_STATUS_CD CHAR(2) NOT NULL DEFAULT 'NV',
  ADD CONSTRAINT C_PEER_C_VALIDATION_STATUS FOREIGN KEY (VALIDATION_STATUS_CD) REFERENCES C_VALIDATION_STATUS (STATUS_CD);
-- 28
ALTER TABLE C_PEER_SUB
  ADD COLUMN SCOPE_TYPE CHAR(2) NOT NULL DEFAULT 'FL',
  ADD CONSTRAINT C_PEER_SUB_C_SCOPE FOREIGN KEY (SCOPE_TYPE) REFERENCES C_SUB_SCOPE_TYPE (TYPE_CD);
-- 29
ALTER TABLE C_PEER_SUB
  ADD COLUMN PROCESSED_DATE TIMESTAMP;
-- 30
ALTER TABLE C_PEER_SUB
  ADD COLUMN ACCESS_TYPE CHAR(2) NOT NULL DEFAULT 'PB',
  ADD CONSTRAINT C_PEER_SUB_C_ACCESS FOREIGN KEY (ACCESS_TYPE) REFERENCES C_ACCESS_TYPE (TYPE_CD);
-- 31
ALTER TABLE C_SOLUTION
  ADD COLUMN ORIGIN VARCHAR(512);
-- 32   
ALTER TABLE C_SOLUTION_REV
  ADD COLUMN ORIGIN VARCHAR(512);
-- 33
ALTER TABLE C_SOLUTION_REV
  ADD COLUMN SOURCE_ID CHAR(36),
  ADD CONSTRAINT C_SOLUTION_REV_C_PEER FOREIGN KEY (SOURCE_ID) REFERENCES C_PEER (PEER_ID);
-- 34  
CREATE TABLE C_STEP_RESULT (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  STEP_CD CHAR(2) NOT NULL,
  STATUS_CD CHAR(2) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  TRACKING_ID CHAR(36),
  SOLUTION_ID CHAR(36),
  REVISION_ID CHAR(36),
  ARTIFACT_ID CHAR(36),
  USER_ID CHAR(36),
  RESULT VARCHAR(8192),
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP,
  CONSTRAINT C_STEP_RESULT_C_STEP_CD FOREIGN KEY (STEP_CD) REFERENCES C_STEP_TYPE (TYPE_CD),
  CONSTRAINT C_STEP_RESULT_STATUS_CD FOREIGN KEY (STATUS_CD) REFERENCES C_STEP_STATUS (STATUS_CD),
  CONSTRAINT C_STEP_RESULT_C_SOLUTION FOREIGN KEY (SOLUTION_ID) REFERENCES C_SOLUTION (SOLUTION_ID),
  CONSTRAINT C_STEP_RESULT_C_SOLUTION_REV FOREIGN KEY (REVISION_ID) REFERENCES C_SOLUTION_REV (REVISION_ID),
  CONSTRAINT C_STEP_RESULT_C_ARTIFACT FOREIGN KEY (ARTIFACT_ID) REFERENCES C_ARTIFACT (ARTIFACT_ID),
  CONSTRAINT C_STEP_RESULT_C_USER FOREIGN KEY (USER_ID) REFERENCES C_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
