-- Script to downgrade database used by the Common Data Service
-- FROM version 1.8.x TO version 1.7.x.
-- No database is created or specified to allow flexible deployment!

ALTER TABLE C_SOLUTION_WEB 
DROP COLUMN LAST_DOWNLOAD;

DROP TABLE IF EXISTS C_SOLUTION_DOWNLOAD;
CREATE TABLE C_SOLUTION_DOWNLOAD (
  SOLUTION_ID CHAR(36) NOT NULL,
  DOWNLOAD_TIME BIGINT NOT NULL,
  USER_ID CHAR(36) NOT NULL,
  PRIMARY KEY (SOLUTION_ID, DOWNLOAD_TIME, USER_ID),
  CONSTRAINT C_SOLUTION_DOWNLOAD_C_SOLUTION FOREIGN KEY (SOLUTION_ID) REFERENCES C_SOLUTION (SOLUTION_ID),
  CONSTRAINT C_SOLUTION_DOWNLOAD_C_USER FOREIGN KEY (USER_ID) REFERENCES C_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
