-- Script to upgrade database used by the Common Data Service
-- FROM version 1.9.x TO version 1.10.x.
-- No database is created or specified to allow flexible deployment!

ALTER TABLE C_SOLUTION_VALIDATION MODIFY DETAIL VARCHAR(8192);

CREATE TABLE C_THREAD (
  THREAD_ID CHAR(36) NOT NULL PRIMARY KEY,
  TITLE VARCHAR(128),
  URL VARCHAR(512) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE C_COMMENT (
  COMMENT_ID CHAR(36) NOT NULL PRIMARY KEY,
  THREAD_ID CHAR(36) NOT NULL,
  PARENT_ID CHAR(36),
  USER_ID CHAR(36) NOT NULL,
  TEXT VARCHAR(8192) NOT NULL,
  URL VARCHAR(512),
  CREATED_DATE TIMESTAMP NOT NULL,
  MODIFIED_DATE TIMESTAMP NOT NULL,
  CONSTRAINT C_COMMENT_C_THREAD FOREIGN KEY (THREAD_ID) REFERENCES C_THREAD (THREAD_ID),
  CONSTRAINT C_COMMENT_C_PARENT FOREIGN KEY (PARENT_ID) REFERENCES C_COMMENT (COMMENT_ID),
  CONSTRAINT C_COMMENT_C_USER FOREIGN KEY (USER_ID) REFERENCES C_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
