/*-
 * ===============LICENSE_START=======================================================
 * Acumos
 * ===================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
 * ===================================================================================
 * This Acumos software file is distributed by AT&T and Tech Mahindra
 * under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *  
 *      http://www.apache.org/licenses/LICENSE-2.0
 *  
 * This file is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ===============LICENSE_END=========================================================
 */

package org.acumos.cds.domain;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.GenericGenerator;

/**
 * Model for an artifact.
 * 
 * Participates in a many-to-many relationship with a solution revision; all the
 * annotations are on that other class.
 */
@Entity
@Table(name = "C_ARTIFACT")
public final class MLPArtifact extends MLPTimestampedEntity implements Serializable {

	private static final long serialVersionUID = 814823907210569812L;

	@Id
	@GeneratedValue(generator = "customUseOrGenerate")
	@GenericGenerator(name = "customUseOrGenerate", strategy = "org.acumos.cds.util.UseExistingOrNewUUIDGenerator")
	@Column(name = "ARTIFACT_ID", updatable = false, nullable = false, columnDefinition = "CHAR(36)")
	// Generated by DB; NotNull annotation not needed
	private String artifactId;

	@Column(name = "VERSION", nullable = false, columnDefinition = "VARCHAR(25)")
	@NotNull(message = "Version cannot be null")
	@Size(max = 25)
	private String version;

	/**
	 * This exposes the database code for simplicity. Alternately this column could
	 * be mapped using @ManyToOne and @JoinColumn as an MLPArtifactType object.
	 */
	@Column(name = "ARTIFACT_TYPE_CD", nullable = false, columnDefinition = "CHAR(2)")
	@NotNull(message = "The type code cannot be null")
	@Size(max = 2)
	private String artifactTypeCode;

	@Column(name = "NAME", nullable = false, columnDefinition = "VARCHAR(100)")
	@NotNull(message = "Artifact name cannot be null")
	@Size(max = 100)
	private String name;

	@Column(name = "DESCRIPTION", columnDefinition = "VARCHAR(512)")
	@Size(max = 512)
	private String description;

	@Column(name = "URI", nullable = false, columnDefinition = "VARCHAR(512)")
	@NotNull(message = "Artifact URI cannot be null")
	@Size(max = 512)
	private String uri;

	@Column(name = "OWNER_ID", nullable = false, columnDefinition = "CHAR(36)")
	@NotNull(message = "OwnerID cannot be null")
	@Size(max = 36)
	private String ownerId;

	@Column(name = "SIZE", nullable = false, columnDefinition = "INT")
	@NotNull(message = "Size cannot be null")
	private Integer size;

	@Column(name = "METADATA", columnDefinition = "VARCHAR(1024)")
	@Size(max = 1024)
	private String metadata;

	/**
	 * No-arg constructor.
	 */
	public MLPArtifact() {
		// no-arg constructor
	}

	/**
	 * This constructor accepts the required fields; i.e., the minimum that the user
	 * must supply to create a valid instance.
	 * 
	 * @param version
	 *            Version string
	 * @param artifactTypeCode
	 *            Valid artifact type code
	 * @param name
	 *            Name
	 * @param uri
	 *            URI
	 * @param ownerId
	 *            User ID for owner
	 * @param size
	 *            Length
	 */
	public MLPArtifact(String version, String artifactTypeCode, String name, String uri, String ownerId, int size) {
		this.version = version;
		this.artifactTypeCode = artifactTypeCode;
		this.name = name;
		this.uri = uri;
		this.ownerId = ownerId;
		this.size = size;
	}

	public String getArtifactId() {
		return artifactId;
	}

	public void setArtifactId(String artifactId) {
		this.artifactId = artifactId;
	}

	public String getArtifactTypeCode() {
		return artifactTypeCode;
	}

	/**
	 * @param artifactTypeCode
	 *            A value obtained by calling
	 *            {@link org.acumos.cds.ArtifactTypeCode#toString()}.
	 */
	public void setArtifactTypeCode(String artifactTypeCode) {
		this.artifactTypeCode = artifactTypeCode;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUri() {
		return uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

	public Integer getSize() {
		return size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public String getMetadata() {
		return metadata;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

	@Override
	public boolean equals(Object that) {
		if (that == null)
			return false;
		if (!(that instanceof MLPArtifact))
			return false;
		MLPArtifact thatObj = (MLPArtifact) that;
		return Objects.equals(artifactId, thatObj.artifactId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(artifactId, ownerId, artifactTypeCode, description, version, uri);
	}

	@Override
	public String toString() {
		return this.getClass().getName() + "[artifactId=" + artifactId + ", ownerId=" + ownerId + ", artifactTypeCode="
				+ artifactTypeCode + ", description=" + description + ", version=" + version + ", uri=" + uri
				+ ", created=" + getCreated() + ", modified=" + getModified() + "]";
	}

}
